export const SEEDER_VOCABULARY = {
  // 100 Adjectives
  adjectives: [
    'Silent',
    'Golden',
    'Lost',
    'Midnight',
    'Broken',
    'Eternal',
    'Wild',
    'Dark',
    'Blue',
    'Crimson',
    'Hidden',
    'Mystic',
    'Fading',
    'Lonely',
    'Ancient',
    'Velvet',
    'Radiant',
    'Frozen',
    'Savage',
    'Melodic',
    'Infinite',
    'Bitter',
    'Sweet',
    'Deep',
    'Pale',
    'Silver',
    'Shadowy',
    'Burning',
    'Cold',
    'Vibrant',
    'Haunted',
    'Gentle',
    'Harsh',
    'Electric',
    'Acoustic',
    'Solar',
    'Lunar',
    'Cosmic',
    'Urban',
    'Rural',
    'Modern',
    'Classic',
    'Secret',
    'Public',
    'Heavy',
    'Light',
    'Rapid',
    'Slow',
    'Divine',
    'Mortal',
    'Glorious',
    'Tragic',
    'Brave',
    'Cunning',
    'Pure',
    'Grim',
    'Bright',
    'Dim',
    'Distant',
    'Nearby',
    'Abstract',
    'Concrete',
    'Solid',
    'Liquid',
    'Neon',
    'Dusty',
    'Empty',
    'Full',
    'Young',
    'Old',
    'Famous',
    'Unknown',
    'Quiet',
    'Loud',
    'Hard',
    'Soft',
    'Sharp',
    'Dull',
    'Smooth',
    'Rough',
    'Organic',
    'Plastic',
    'Steel',
    'Stone',
    'Wooden',
    'Magic',
    'Logical',
    'Angry',
    'Calm',
    'Proud',
    'Virtual',
    'Real',
    'Fake',
    'Holy',
    'Noble',
    'Grand',
    'Simple',
    'Complex',
    'Royal',
    'Common',
  ],

  // 100 Nouns
  nouns: [
    'Echo',
    'Dream',
    'River',
    'Soul',
    'Shadow',
    'Flame',
    'Heart',
    'Storm',
    'Light',
    'Rain',
    'Ocean',
    'Forest',
    'Mountain',
    'Spirit',
    'Voice',
    'Road',
    'Star',
    'Wind',
    'Night',
    'Fire',
    'World',
    'Heaven',
    'Hell',
    'Earth',
    'Moon',
    'Sun',
    'Sky',
    'Bird',
    'Wolf',
    'Lion',
    'City',
    'Village',
    'Tower',
    'Bridge',
    'Gate',
    'Key',
    'Lock',
    'Mirror',
    'Glass',
    'Gold',
    'Blood',
    'Bone',
    'Skin',
    'Eye',
    'Hand',
    'Breath',
    'Song',
    'Dance',
    'Beat',
    'Note',
    'Time',
    'Space',
    'Edge',
    'Core',
    'Path',
    'Way',
    'Line',
    'Circle',
    'Square',
    'Point',
    'Hero',
    'King',
    'Queen',
    'Ghost',
    'Angel',
    'Demon',
    'Child',
    'Man',
    'Woman',
    'Friend',
    'Weapon',
    'Shield',
    'Crown',
    'Throne',
    'Book',
    'Page',
    'Word',
    'Letter',
    'Sound',
    'Silence',
    'Summer',
    'Winter',
    'Spring',
    'Autumn',
    'Morning',
    'Evening',
    'Day',
    'Week',
    'Year',
    'Era',
    'Truth',
    'Lie',
    'War',
    'Peace',
    'Joy',
    'Pain',
    'Fear',
    'Love',
    'Hate',
    'Life',
  ],

  // 100 Contexts (Sự kết hợp giữa giới từ và danh từ hoặc hậu tố)
  contexts: [
    'in the Dark',
    'of Heaven',
    'from Mars',
    'Underground',
    'Forever',
    'Part II',
    'Legacy',
    'Remastered',
    'in Summer',
    'of Silence',
    'Beneath the Stars',
    'Across the Sea',
    'Inside the Mind',
    'Beyond Time',
    'Without Fear',
    'for You',
    'with Me',
    'through Fire',
    'over Clouds',
    'against All',
    'at Night',
    'on Earth',
    'under Pressure',
    'behind Walls',
    'into Void',
    'around World',
    'near Edge',
    'off Shore',
    'among Us',
    'between Worlds',
    'during Rain',
    'since Dawn',
    'until End',
    'before Storm',
    'after Life',
    'above All',
    'below Zero',
    'within Reach',
    'outside Box',
    'towards Light',
    'away Now',
    'down Town',
    'up High',
    'back Home',
    'forward Fast',
    'sideways Always',
    'again Soon',
    'never More',
    'once Again',
    'twice Shy',
    'alone Tonight',
    'together Now',
    'everywhere Now',
    'somewhere Else',
    'nowhere Fast',
    'always There',
    'sometimes Maybe',
    'often True',
    'seldom Heard',
    'rarely Seen',
    'highly Likely',
    'deeply Felt',
    'wildly Free',
    'slowly Dying',
    'quickly Gone',
    'quietly Kept',
    'loudly Said',
    'hardly Try',
    'softly Spoken',
    'brightly Lit',
    'darkly Seen',
    'purely Made',
    'surely Done',
    'really Good',
    'truly Yours',
    'mostly Cloudy',
    'partly Sunny',
    'wholly Owned',
    'fully Loaded',
    'only One',
    'just Once',
    'even If',
    'still Here',
    'yet Again',
    'already Done',
    'almost There',
    'maybe Tomorrow',
    'perhaps Today',
    'definitely Not',
    'probably So',
    'certainly True',
    'actually Happening',
    'basically Simple',
    'finally Over',
    'initially Started',
    'lastly Said',
    'namely This',
    'shortly After',
    'simply Because',
    'virtually Real',
  ],
};
